name: DiffReceipt
on:
  pull_request:
permissions:
  contents: read
jobs:
  receipt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0
      - uses: smeltzfinn-source/diffreceipt-action@ad03162342b610e64b9eff11158703a3f630b913
