name: DiffReceipt
on:
  pull_request:
permissions:
  contents: read
jobs:
  receipt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          fetch-depth: 0
      - uses: smeltzfinn-source/diffreceipt-action@7d6ad2828ef0e9f888c28c646fd2e5ee542c2313
